/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latorre.Vista;

import javax.swing.table.DefaultTableModel;
import latorre.Modelo.Cliente;

/**
 *
 * @author programadorac
 */
public class ClienteTodas extends javax.swing.JFrame {

    /**
     * Creates new form ClienteTodas
     */
    public ClienteTodas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        jLabel1.setText("Clientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        tblCliente.setModel(new DefaultTableModel());
        jScrollPane1.setViewportView(tblCliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1330, 340));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 90, 50));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 60, 50));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 100, 50));

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 90, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1330, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.limpiar_tabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ClienteNuevo cln = new ClienteNuevo();
        cln.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.limpiar_tabla();
    }//GEN-LAST:event_formWindowActivated

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.modificar_cliente();
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteTodas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteTodas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteTodas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteTodas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteTodas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables

    
    
    protected void limpiar_tabla(){
        DefaultTableModel modeloTabla2 = new DefaultTableModel();
        modeloTabla2.addColumn("Nit");
        modeloTabla2.addColumn("Primer Nombre");
        modeloTabla2.addColumn("Segundo Nombre");
        modeloTabla2.addColumn("Primer Apellido");
        modeloTabla2.addColumn("Segundo Apellido");
        modeloTabla2.addColumn("Direccion");
        modeloTabla2.addColumn("Email");
        modeloTabla2.addColumn("Telefono");
        modeloTabla2.addColumn("Municipio");
        modeloTabla2.addColumn("Departmento");
        modeloTabla2.addColumn("ID Municipio");
        modeloTabla2.addColumn("ID Departmento");
        
        Cliente cl = new Cliente();
        String[][] datos = cl.consultar_campos_nombres();
        for(String[] linea: datos){
            modeloTabla2.addRow(linea);
        }
        
        this.tblCliente.setModel(modeloTabla2);

        this.tblCliente.getColumnModel().getColumn(10).setMaxWidth(10);
        this.tblCliente.getColumnModel().getColumn(10).setMinWidth(10);
        this.tblCliente.getColumnModel().getColumn(10).setPreferredWidth(10);
        
        this.tblCliente.getColumnModel().getColumn(11).setMaxWidth(11);
        this.tblCliente.getColumnModel().getColumn(11).setMinWidth(11);
        this.tblCliente.getColumnModel().getColumn(11).setPreferredWidth(11);

        /*
        this.tblCliente.removeColumn(this.tblCliente.getColumnModel().getColumn(10));
        this.tblCliente.removeColumn(this.tblCliente.getColumnModel().getColumn(10));
*/
    }
    
    protected void modificar_cliente(){
        
         ClienteActualizar cla = new ClienteActualizar();
        cla.setVisible(true);
        int fila = this.tblCliente.getSelectedRow();
        String NIT = this.tblCliente.getValueAt(fila, 0).toString();
        String nombre1  = this.tblCliente.getValueAt(fila, 1).toString();
        String  nombre2 = this.tblCliente.getValueAt(fila, 2).toString();
        String  apellido1 = this.tblCliente.getValueAt(fila, 3).toString();
        String  apellido2 = this.tblCliente.getValueAt(fila, 4).toString();
        String  direccion = this.tblCliente.getValueAt(fila, 5).toString();
        String  email = this.tblCliente.getValueAt(fila, 6).toString();
        String  telefono  = this.tblCliente.getValueAt(fila, 7).toString();
        String municipio = this.tblCliente.getValueAt(fila, 10).toString(); //MENOS UNO PARA QUE SE EL INDEX INDICADO
        String departamento = this.tblCliente.getValueAt(fila, 11).toString();
       
        cla.set_datos(NIT, nombre1, nombre2, apellido1, apellido2, direccion, email, telefono,municipio,departamento);
         
    }
}
